version: '3'
services:
  spark-master:
    image: apache/spark
    container_name: spark-master
    command: start-master.sh
    ports:
      - "8080:8080" # web ui
      - "7077:7077" # master port
  
  spark-worker:
    image: apache/spark
    container_name: spark-worker
    command: start-worker.sh spark://spark-master:0777
    depends_on:
      - spark-master
    ports:
      - 8081:8081 # worker web ui
  
  jupyter:
    image: jupyter/pyspark-notebook
    container_name: spark-jupyter
    environment:
      - SPARK_MASTER = spark://spark-master:7077
    ports:
      - 8888:8888 #jupyter
    volumes:
      - ./notebooks:/home/jovyan/work
    depends_on:
      - spark-master
      - spark-worker